import ScrollSpy from 'react-scrollspy-navigation';
import ArrowDropDownIcon from '@mui/icons-material/ArrowDropDown';
// recursively crawls through the tree generated by @stefanprobst/rehype-extract-toc
// and generates the table of contents
function recursiveToc(toc, collapse, level = 0) {
    // ignore first level headers, head straight to h2
    const currLevel = level ? toc.map((li) => (
          <li key={li.id}>
            <div className="w-fit">
                <a href={`#${li.id}`} className="toc-links">
                    <div className="toc-url-container">
                        {li.value}
                        {collapse && li.children ? <span className="ml-1"><ArrowDropDownIcon className="transition-all -rotate-90"/></span> : <></>}
                    </div>
                </a>
            </div>
            <div>{li.children ? recursiveToc(li.children, collapse, level + 1) : <></>}</div>
          </li>
    )) : toc.map((li) => (
        <div key={li.id}>
            {li.children ? recursiveToc(li.children, collapse, level + 1) : <></>}
        </div>
    ))

    return ( level ? 
        <ul className="list-none ps-4 toc">
            {currLevel}
        </ul> : <>{currLevel}</>
    )
}

export default function TableOfContents({toc, frontmatter}) {

    return (
        <ScrollSpy activeClass="toc-current" offsetTop="80">      
            <nav className={`toc${frontmatter.collapseToc ? " toc-collapse" : ""}`}>
                {recursiveToc(toc, frontmatter.collapseToc)}
            </nav>
        </ScrollSpy>
    )
}