name: Formatting Check

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  pull-requests: read

jobs:
  check-formatting:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment using Prettier
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "23"

      # Install Prettier
      - name: Install Dependencies
        run: |
          npm install --save-dev prettier

      # Run Prettier in check mode (this will only check, not reformat)
      - name: Run Prettier (Check Mode)
        run: |
          npx prettier --check .
